export interface Product {
  id: string
  name: string
  description: string
  price: number
  originalPrice?: number
  rating: number
  reviewCount: number
  brand: string
  image: string
  images?: string[]
  category: string
  stock: number
  sku: string
  merchantId: string
  tags: string[]
  featured?: boolean
  popularity: number
  variants?: ProductVariant[]
  specifications?: Record<string, string>
  shippingInfo?: string
  returnPolicy?: string
  status?: "draft" | "published" | "archived"
  productType?: "physical" | "digital"
  weight?: number // in kg for physical products
  dimensions?: {
    length: number
    width: number
    height: number
  }
  isBundle?: boolean
  bundleItems?: string[] // Product IDs that make up the bundle
  lowStockThreshold?: number
  allowBackorders?: boolean
  trackInventory?: boolean
  barcode?: string
  costPrice?: number // For profit margin calculations
  compareAtPrice?: number // Additional comparison price
  taxable?: boolean
  requiresShipping?: boolean
  metaTitle?: string
  metaDescription?: string
  createdAt?: string
  updatedAt?: string
}

export interface Order {
  id: string
  userId: string
  userName: string
  userEmail: string
  items: OrderItem[]
  total: number
  status: "pending" | "processing" | "shipped" | "delivered" | "cancelled"
  createdAt: string
}

export interface OrderItem {
  productId: string
  productName: string
  quantity: number
  price: number
}

export interface CartItem {
  product: Product
  quantity: number
}

export interface Category {
  id: string
  name: string
  description: string
  image: string
  productCount: number
}

export interface Promotion {
  id: string
  title: string
  description: string
  discount: number
  code: string
  expiresAt: string
  image: string
}

export interface ProductVariant {
  id: string
  name: string
  options: string[]
}

export interface Review {
  id: string
  productId: string
  userName: string
  rating: number
  comment: string
  date: string
  verified: boolean
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life.",
    price: 299.99,
    originalPrice: 349.99,
    rating: 4.5,
    reviewCount: 128,
    brand: "AudioTech",
    image: "/premium-black-wireless-headphones.jpg",
    images: [
      "/premium-black-wireless-headphones.jpg",
      "/premium-black-wireless-headphones.jpg",
      "/premium-black-wireless-headphones.jpg",
    ],
    category: "Electronics",
    stock: 50,
    sku: "AT-WH-001",
    merchantId: "2",
    tags: ["wireless", "noise-cancelling", "bluetooth", "premium"],
    featured: true,
    popularity: 95,
    variants: [
      { id: "color", name: "Color", options: ["Black", "Silver", "Blue"] },
      { id: "size", name: "Size", options: ["Standard", "Large"] },
    ],
    specifications: {
      "Battery Life": "30 hours",
      Connectivity: "Bluetooth 5.0",
      Weight: "250g",
      "Noise Cancellation": "Active",
      Warranty: "2 years",
    },
    shippingInfo: "Free shipping on orders over $50. Estimated delivery 3-5 business days.",
    returnPolicy: "30-day return policy. Items must be in original condition.",
    status: "published",
    productType: "physical",
    weight: 0.25,
    dimensions: { length: 15, width: 10, height: 3 },
    isBundle: false,
    lowStockThreshold: 10,
    allowBackorders: false,
    trackInventory: true,
    barcode: "1234567890123",
    costPrice: 150,
    compareAtPrice: 399.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Premium Wireless Headphones",
    metaDescription: "Experience crystal clear sound with noise cancellation.",
    createdAt: "2023-10-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    name: "Minimalist Leather Wallet",
    description: "Slim leather wallet with RFID protection and space for 8 cards.",
    price: 59.99,
    rating: 4.8,
    reviewCount: 342,
    brand: "LeatherCraft",
    image: "/black-leather-wallet-minimalist.jpg",
    images: ["/black-leather-wallet-minimalist.jpg", "/black-leather-wallet-minimalist.jpg"],
    category: "Accessories",
    stock: 100,
    sku: "LC-WL-002",
    merchantId: "2",
    tags: ["leather", "rfid", "minimalist", "slim"],
    popularity: 88,
    variants: [{ id: "color", name: "Color", options: ["Black", "Brown", "Tan"] }],
    specifications: {
      Material: "Genuine Leather",
      "Card Slots": "8",
      "RFID Protection": "Yes",
      Dimensions: "10cm x 7cm x 1cm",
    },
    shippingInfo: "Standard shipping $5. Free over $50.",
    returnPolicy: "30-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.1,
    dimensions: { length: 10, width: 7, height: 1 },
    isBundle: false,
    lowStockThreshold: 20,
    allowBackorders: false,
    trackInventory: true,
    barcode: "0987654321098",
    costPrice: 30,
    compareAtPrice: 79.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Minimalist Leather Wallet",
    metaDescription: "Stay organized with this stylish leather wallet.",
    createdAt: "2023-10-02T00:00:00Z",
    updatedAt: "2024-01-18T14:20:00Z",
  },
  {
    id: "3",
    name: "Smart Fitness Watch",
    description: "Track your fitness goals with heart rate monitoring, GPS, and water resistance.",
    price: 199.99,
    originalPrice: 249.99,
    rating: 4.3,
    reviewCount: 215,
    brand: "FitTrack",
    image: "/black-fitness-smartwatch.jpg",
    images: ["/black-fitness-smartwatch.jpg", "/black-fitness-smartwatch.jpg"],
    category: "Electronics",
    stock: 75,
    sku: "FT-SW-003",
    merchantId: "2",
    tags: ["fitness", "smartwatch", "gps", "waterproof"],
    featured: true,
    popularity: 92,
    variants: [
      { id: "color", name: "Color", options: ["Black", "Red", "Blue"] },
      { id: "size", name: "Size", options: ["Small", "Medium", "Large"] },
    ],
    specifications: {
      Display: "1.4 inch AMOLED",
      "Water Resistance": "5ATM",
      "Battery Life": "7 days",
      GPS: "Built-in",
      Sensors: "Heart Rate, SpO2, Sleep Tracking",
    },
    shippingInfo: "Free shipping. Delivery in 2-4 days.",
    returnPolicy: "30-day return policy for unopened items.",
    status: "published",
    productType: "digital",
    weight: null,
    dimensions: null,
    isBundle: false,
    lowStockThreshold: 5,
    allowBackorders: false,
    trackInventory: false,
    barcode: "5678901234567",
    costPrice: 120,
    compareAtPrice: 299.99,
    taxable: true,
    requiresShipping: false,
    metaTitle: "Smart Fitness Watch",
    metaDescription: "Monitor your health and fitness with this smartwatch.",
    createdAt: "2023-10-03T00:00:00Z",
    updatedAt: "2024-01-20T08:15:00Z",
  },
  {
    id: "4",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable, sustainable t-shirt made from 100% organic cotton.",
    price: 29.99,
    rating: 4.6,
    reviewCount: 456,
    brand: "EcoWear",
    image: "/black-cotton-tshirt.jpg",
    images: ["/black-cotton-tshirt.jpg"],
    category: "Clothing",
    stock: 200,
    sku: "EW-TS-004",
    merchantId: "2",
    tags: ["organic", "cotton", "sustainable", "comfortable"],
    popularity: 78,
    variants: [
      { id: "color", name: "Color", options: ["Black", "White", "Gray", "Navy"] },
      { id: "size", name: "Size", options: ["XS", "S", "M", "L", "XL", "XXL"] },
    ],
    specifications: {
      Material: "100% Organic Cotton",
      Fit: "Regular",
      "Care Instructions": "Machine wash cold",
      Certification: "GOTS Certified",
    },
    shippingInfo: "Standard shipping available.",
    returnPolicy: "Free returns within 60 days.",
    status: "published",
    productType: "physical",
    weight: 0.15,
    dimensions: { length: 40, width: 30, height: 20 },
    isBundle: false,
    lowStockThreshold: 30,
    allowBackorders: true,
    trackInventory: true,
    barcode: "4567890123456",
    costPrice: 15,
    compareAtPrice: 49.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Organic Cotton T-Shirt",
    metaDescription: "Wear comfortably with this eco-friendly t-shirt.",
    createdAt: "2023-10-04T00:00:00Z",
    updatedAt: "2024-01-21T12:00:00Z",
  },
  {
    id: "5",
    name: "Stainless Steel Water Bottle",
    description: "Insulated water bottle keeps drinks cold for 24 hours or hot for 12 hours.",
    price: 34.99,
    rating: 4.7,
    reviewCount: 523,
    brand: "HydroLife",
    image: "/black-stainless-water-bottle.jpg",
    images: ["/black-stainless-water-bottle.jpg"],
    category: "Accessories",
    stock: 150,
    sku: "HL-WB-005",
    merchantId: "2",
    tags: ["insulated", "stainless-steel", "eco-friendly", "durable"],
    popularity: 85,
    variants: [
      { id: "color", name: "Color", options: ["Black", "Blue", "Pink", "Green"] },
      { id: "size", name: "Size", options: ["500ml", "750ml", "1L"] },
    ],
    specifications: {
      Material: "Stainless Steel 18/8",
      Insulation: "Double-wall vacuum",
      "Cold Retention": "24 hours",
      "Hot Retention": "12 hours",
      "BPA Free": "Yes",
    },
    shippingInfo: "Ships in 1-2 days.",
    returnPolicy: "Lifetime warranty on defects.",
    status: "published",
    productType: "physical",
    weight: 0.5,
    dimensions: { length: 20, width: 10, height: 5 },
    isBundle: false,
    lowStockThreshold: 25,
    allowBackorders: false,
    trackInventory: true,
    barcode: "7890123456789",
    costPrice: 20,
    compareAtPrice: 59.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Stainless Steel Water Bottle",
    metaDescription: "Stay hydrated with this durable water bottle.",
    createdAt: "2023-10-05T00:00:00Z",
    updatedAt: "2024-01-22T16:30:00Z",
  },
  {
    id: "6",
    name: "Professional Camera Lens",
    description: "50mm f/1.8 prime lens for stunning portrait photography.",
    price: 449.99,
    originalPrice: 549.99,
    rating: 4.9,
    reviewCount: 89,
    brand: "OpticsPro",
    image: "/black-camera-lens.jpg",
    images: ["/black-camera-lens.jpg", "/black-camera-lens.jpg"],
    category: "Electronics",
    stock: 30,
    sku: "OP-CL-006",
    merchantId: "2",
    tags: ["camera", "lens", "photography", "professional"],
    featured: true,
    popularity: 90,
    variants: [{ id: "mount", name: "Mount Type", options: ["Canon EF", "Nikon F", "Sony E"] }],
    specifications: {
      "Focal Length": "50mm",
      "Maximum Aperture": "f/1.8",
      "Lens Construction": "6 elements in 5 groups",
      "Minimum Focus Distance": "45cm",
      "Filter Size": "52mm",
    },
    shippingInfo: "Free expedited shipping. Arrives in 1-3 days.",
    returnPolicy: "14-day return policy for unopened items.",
    status: "published",
    productType: "physical",
    weight: 0.3,
    dimensions: { length: 50, width: 30, height: 10 },
    isBundle: false,
    lowStockThreshold: 5,
    allowBackorders: false,
    trackInventory: true,
    barcode: "3210987654321",
    costPrice: 200,
    compareAtPrice: 499.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Professional Camera Lens",
    metaDescription: "Capture stunning portraits with this high-quality lens.",
    createdAt: "2023-10-06T00:00:00Z",
    updatedAt: "2024-01-23T09:45:00Z",
  },
  {
    id: "7",
    name: "Classic Oxford Shirt",
    description: "Timeless oxford shirt in premium cotton, perfect for any occasion.",
    price: 89.99,
    rating: 4.6,
    reviewCount: 182,
    brand: "Gentleman's Choice",
    image: "/elegant-white-oxford-shirt-on-model.jpg",
    images: ["/elegant-white-oxford-shirt-on-model.jpg"],
    category: "Men",
    stock: 85,
    sku: "GC-OX-007",
    merchantId: "2",
    tags: ["cotton", "formal", "casual", "classic"],
    popularity: 87,
    variants: [
      { id: "color", name: "Color", options: ["White", "Light Blue", "Pink"] },
      { id: "size", name: "Size", options: ["S", "M", "L", "XL", "XXL"] },
    ],
    specifications: {
      Material: "100% Premium Cotton",
      Fit: "Slim Fit",
      "Care Instructions": "Machine wash cold",
      Style: "Button-down collar",
    },
    shippingInfo: "Free shipping on orders over $50.",
    returnPolicy: "30-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.3,
    dimensions: { length: 30, width: 25, height: 3 },
    isBundle: false,
    lowStockThreshold: 15,
    allowBackorders: true,
    trackInventory: true,
    barcode: "6789012345678",
    costPrice: 45,
    compareAtPrice: 129.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Classic Oxford Shirt",
    metaDescription: "Elegant oxford shirt for the modern gentleman.",
    createdAt: "2023-10-07T00:00:00Z",
    updatedAt: "2024-01-24T11:15:00Z",
  },
  {
    id: "8",
    name: "Tailored Wool Blazer",
    description: "Sophisticated wool blazer with modern tailoring and exceptional comfort.",
    price: 349.99,
    originalPrice: 449.99,
    rating: 4.8,
    reviewCount: 95,
    brand: "Gentleman's Choice",
    image: "/navy-blue-wool-blazer-on-model.jpg",
    images: ["/navy-blue-wool-blazer-on-model.jpg"],
    category: "Men",
    stock: 42,
    sku: "GC-BL-008",
    merchantId: "2",
    tags: ["wool", "formal", "blazer", "tailored"],
    featured: true,
    popularity: 93,
    variants: [
      { id: "color", name: "Color", options: ["Navy", "Charcoal", "Black"] },
      { id: "size", name: "Size", options: ["38", "40", "42", "44", "46"] },
    ],
    specifications: {
      Material: "85% Wool, 15% Polyester",
      Lining: "Full viscose lining",
      Fit: "Modern Slim Fit",
      Buttons: "2-button closure",
      Pockets: "Two side pockets, one chest pocket",
    },
    shippingInfo: "Free expedited shipping.",
    returnPolicy: "60-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.9,
    dimensions: { length: 35, width: 30, height: 5 },
    isBundle: false,
    lowStockThreshold: 10,
    allowBackorders: false,
    trackInventory: true,
    barcode: "8901234567890",
    costPrice: 180,
    compareAtPrice: 499.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Tailored Wool Blazer",
    metaDescription: "Elevate your style with this premium wool blazer.",
    createdAt: "2023-10-08T00:00:00Z",
    updatedAt: "2024-01-25T09:30:00Z",
  },
  {
    id: "9",
    name: "Premium Chino Trousers",
    description: "Versatile chino trousers crafted from stretch cotton for all-day comfort.",
    price: 79.99,
    rating: 4.5,
    reviewCount: 267,
    brand: "Urban Essentials",
    image: "/beige-chino-trousers-on-model.jpg",
    images: ["/beige-chino-trousers-on-model.jpg"],
    category: "Men",
    stock: 120,
    sku: "UE-CH-009",
    merchantId: "2",
    tags: ["chinos", "casual", "stretch", "versatile"],
    popularity: 82,
    variants: [
      { id: "color", name: "Color", options: ["Beige", "Navy", "Olive", "Black"] },
      { id: "size", name: "Size", options: ["30", "32", "34", "36", "38", "40"] },
    ],
    specifications: {
      Material: "97% Cotton, 3% Elastane",
      Fit: "Slim Fit",
      Closure: "Zip fly with button",
      Pockets: "Side pockets, back welt pockets",
    },
    shippingInfo: "Standard shipping available.",
    returnPolicy: "30-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.4,
    dimensions: { length: 40, width: 30, height: 3 },
    isBundle: false,
    lowStockThreshold: 20,
    allowBackorders: true,
    trackInventory: true,
    barcode: "9012345678901",
    costPrice: 40,
    compareAtPrice: 99.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Premium Chino Trousers",
    metaDescription: "Comfortable and stylish chinos for everyday wear.",
    createdAt: "2023-10-09T00:00:00Z",
    updatedAt: "2024-01-26T14:00:00Z",
  },
  {
    id: "10",
    name: "Merino Wool Sweater",
    description: "Luxurious merino wool sweater with ribbed detailing and exceptional softness.",
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.7,
    reviewCount: 143,
    brand: "Gentleman's Choice",
    image: "/grey-merino-wool-sweater-on-model.jpg",
    images: ["/grey-merino-wool-sweater-on-model.jpg"],
    category: "Men",
    stock: 68,
    sku: "GC-SW-010",
    merchantId: "2",
    tags: ["merino", "wool", "sweater", "luxury"],
    popularity: 89,
    variants: [
      { id: "color", name: "Color", options: ["Grey", "Navy", "Burgundy", "Charcoal"] },
      { id: "size", name: "Size", options: ["S", "M", "L", "XL"] },
    ],
    specifications: {
      Material: "100% Merino Wool",
      Fit: "Regular Fit",
      Neckline: "Crew neck",
      "Care Instructions": "Hand wash cold, lay flat to dry",
    },
    shippingInfo: "Free shipping on orders over $50.",
    returnPolicy: "30-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.5,
    dimensions: { length: 28, width: 24, height: 4 },
    isBundle: false,
    lowStockThreshold: 15,
    allowBackorders: false,
    trackInventory: true,
    barcode: "0123456789012",
    costPrice: 65,
    compareAtPrice: 179.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Merino Wool Sweater",
    metaDescription: "Stay warm in style with this premium merino wool sweater.",
    createdAt: "2023-10-10T00:00:00Z",
    updatedAt: "2024-01-27T10:45:00Z",
  },
  {
    id: "11",
    name: "Leather Derby Shoes",
    description: "Handcrafted leather derby shoes with Goodyear welted construction.",
    price: 249.99,
    rating: 4.9,
    reviewCount: 76,
    brand: "Heritage Footwear",
    image: "/brown-leather-derby-shoes.jpg",
    images: ["/brown-leather-derby-shoes.jpg"],
    category: "Men",
    stock: 54,
    sku: "HF-DS-011",
    merchantId: "2",
    tags: ["leather", "formal", "handcrafted", "shoes"],
    featured: true,
    popularity: 91,
    variants: [
      { id: "color", name: "Color", options: ["Brown", "Black", "Tan"] },
      { id: "size", name: "Size", options: ["7", "8", "9", "10", "11", "12"] },
    ],
    specifications: {
      Material: "Full-grain leather upper",
      Construction: "Goodyear welted",
      Sole: "Leather sole",
      Lining: "Leather lining",
      "Made in": "Italy",
    },
    shippingInfo: "Free shipping and returns.",
    returnPolicy: "60-day return policy.",
    status: "published",
    productType: "physical",
    weight: 1.2,
    dimensions: { length: 30, width: 15, height: 12 },
    isBundle: false,
    lowStockThreshold: 10,
    allowBackorders: false,
    trackInventory: true,
    barcode: "1230987654321",
    costPrice: 125,
    compareAtPrice: 299.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Leather Derby Shoes",
    metaDescription: "Classic derby shoes crafted from premium leather.",
    createdAt: "2023-10-11T00:00:00Z",
    updatedAt: "2024-01-28T15:20:00Z",
  },
  {
    id: "12",
    name: "Silk Tie Collection",
    description: "Premium silk tie with intricate woven pattern, perfect for formal occasions.",
    price: 49.99,
    rating: 4.6,
    reviewCount: 198,
    brand: "Urban Essentials",
    image: "/navy-silk-tie-with-pattern.jpg",
    images: ["/navy-silk-tie-with-pattern.jpg"],
    category: "Men",
    stock: 145,
    sku: "UE-TI-012",
    merchantId: "2",
    tags: ["silk", "tie", "formal", "accessories"],
    popularity: 79,
    variants: [{ id: "color", name: "Color", options: ["Navy", "Burgundy", "Forest Green", "Charcoal"] }],
    specifications: {
      Material: "100% Silk",
      Width: "8cm",
      Length: "150cm",
      Pattern: "Woven geometric",
    },
    shippingInfo: "Standard shipping available.",
    returnPolicy: "14-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.08,
    dimensions: { length: 20, width: 15, height: 2 },
    lowStockThreshold: 25,
    allowBackorders: true,
    trackInventory: true,
    barcode: "3456789012345",
    costPrice: 25,
    compareAtPrice: 69.99,
    taxable: true,
    requiresShipping: true,
    metaTitle: "Silk Tie Collection",
    metaDescription: "Elegant silk ties for the sophisticated gentleman.",
    createdAt: "2023-10-12T00:00:00Z",
    updatedAt: "2024-01-29T11:00:00Z",
  },
  {
    id: "13",
    name: "Cashmere Turtleneck Sweater",
    description: "Ultra-soft cashmere turtleneck sweater with relaxed fit and ribbed hem.",
    price: 189.99,
    originalPrice: 229.99,
    rating: 4.8,
    reviewCount: 156,
    brand: "Elegance",
    image: "/beige-cashmere-turtleneck-sweater-on-model.jpg",
    images: ["/beige-cashmere-turtleneck-sweater-on-model.jpg"],
    category: "Women",
    stock: 67,
    sku: "EL-CS-013",
    merchantId: "2",
    tags: ["cashmere", "turtleneck", "luxury", "winter"],
    featured: true,
    popularity: 94,
    variants: [
      { id: "color", name: "Color", options: ["Beige", "Black", "Ivory", "Camel"] },
      { id: "size", name: "Size", options: ["XS", "S", "M", "L", "XL"] },
    ],
    specifications: {
      Material: "100% Cashmere",
      Fit: "Relaxed Fit",
      "Care Instructions": "Dry clean only",
      Origin: "Scotland",
    },
    shippingInfo: "Free express shipping.",
    returnPolicy: "30-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.35,
    dimensions: { length: 30, width: 25, height: 4 },
    lowStockThreshold: 15,
    trackInventory: true,
    barcode: "2345678901234",
    costPrice: 95,
    compareAtPrice: 249.99,
    taxable: true,
    requiresShipping: true,
  },
  {
    id: "14",
    name: "Silk Midi Dress",
    description: "Flowing silk midi dress with elegant drape and adjustable straps.",
    price: 269.99,
    rating: 4.7,
    reviewCount: 89,
    brand: "Elegance",
    image: "/emerald-green-silk-midi-dress-on-model.jpg",
    images: ["/emerald-green-silk-midi-dress-on-model.jpg"],
    category: "Women",
    stock: 43,
    sku: "EL-MD-014",
    merchantId: "2",
    tags: ["silk", "dress", "evening", "elegant"],
    popularity: 88,
    variants: [
      { id: "color", name: "Color", options: ["Emerald", "Navy", "Burgundy", "Black"] },
      { id: "size", name: "Size", options: ["XS", "S", "M", "L"] },
    ],
    specifications: {
      Material: "100% Silk Charmeuse",
      Length: "Midi (below knee)",
      Closure: "Side zip",
      Lining: "Fully lined",
    },
    shippingInfo: "Free shipping.",
    returnPolicy: "14-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.3,
    dimensions: { length: 35, width: 28, height: 3 },
    lowStockThreshold: 10,
    trackInventory: true,
    barcode: "3456789012345",
    costPrice: 135,
    compareAtPrice: 329.99,
    taxable: true,
    requiresShipping: true,
  },
  {
    id: "15",
    name: "Tailored Trench Coat",
    description: "Classic double-breasted trench coat in water-resistant gabardine.",
    price: 399.99,
    originalPrice: 499.99,
    rating: 4.9,
    reviewCount: 124,
    brand: "Elegance",
    image: "/beige-double-breasted-trench-coat-on-model.jpg",
    images: ["/beige-double-breasted-trench-coat-on-model.jpg"],
    category: "Women",
    stock: 38,
    sku: "EL-TC-015",
    merchantId: "2",
    tags: ["trench", "coat", "classic", "waterproof"],
    featured: true,
    popularity: 96,
    variants: [
      { id: "color", name: "Color", options: ["Beige", "Black", "Navy"] },
      { id: "size", name: "Size", options: ["XS", "S", "M", "L", "XL"] },
    ],
    specifications: {
      Material: "Cotton Gabardine",
      "Water Resistance": "Yes",
      Closure: "Double-breasted with belt",
      Lining: "Full satin lining",
      Pockets: "Two side pockets, inner pocket",
    },
    shippingInfo: "Free express shipping.",
    returnPolicy: "60-day return policy.",
    status: "published",
    productType: "physical",
    weight: 1.1,
    dimensions: { length: 40, width: 35, height: 6 },
    lowStockThreshold: 8,
    trackInventory: true,
    barcode: "4567890123456",
    costPrice: 200,
    compareAtPrice: 599.99,
    taxable: true,
    requiresShipping: true,
  },
  {
    id: "16",
    name: "Wide-Leg Linen Trousers",
    description: "Breathable linen trousers with wide-leg silhouette and elastic waistband.",
    price: 89.99,
    rating: 4.5,
    reviewCount: 203,
    brand: "Summer Breeze",
    image: "/white-wide-leg-linen-trousers-on-model.jpg",
    images: ["/white-wide-leg-linen-trousers-on-model.jpg"],
    category: "Women",
    stock: 92,
    sku: "SB-LT-016",
    merchantId: "2",
    tags: ["linen", "trousers", "summer", "comfortable"],
    popularity: 81,
    variants: [
      { id: "color", name: "Color", options: ["White", "Beige", "Navy", "Olive"] },
      { id: "size", name: "Size", options: ["XS", "S", "M", "L", "XL"] },
    ],
    specifications: {
      Material: "100% European Linen",
      Fit: "Wide Leg",
      Waist: "Elastic waistband with drawstring",
      Pockets: "Side seam pockets",
    },
    shippingInfo: "Standard shipping available.",
    returnPolicy: "30-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.4,
    dimensions: { length: 38, width: 30, height: 3 },
    lowStockThreshold: 18,
    trackInventory: true,
    barcode: "5678901234567",
    costPrice: 45,
    compareAtPrice: 119.99,
    taxable: true,
    requiresShipping: true,
  },
  {
    id: "17",
    name: "Pearl Drop Earrings",
    description: "Elegant freshwater pearl drop earrings with sterling silver posts.",
    price: 79.99,
    rating: 4.8,
    reviewCount: 267,
    brand: "LuxeJewelry",
    image: "/pearl-drop-earrings-on-white-background.jpg",
    images: ["/pearl-drop-earrings-on-white-background.jpg"],
    category: "Accessories",
    stock: 156,
    sku: "LJ-PE-017",
    merchantId: "2",
    tags: ["pearls", "earrings", "jewelry", "elegant"],
    popularity: 85,
    variants: [{ id: "metal", name: "Metal", options: ["Sterling Silver", "14K Gold Plated"] }],
    specifications: {
      "Pearl Type": "Freshwater",
      "Pearl Size": "8-9mm",
      Metal: "Sterling Silver 925",
      Closure: "Post with butterfly back",
    },
    shippingInfo: "Free shipping in gift box.",
    returnPolicy: "30-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.02,
    dimensions: { length: 5, width: 5, height: 2 },
    lowStockThreshold: 30,
    trackInventory: true,
    barcode: "6789012345678",
    costPrice: 40,
    compareAtPrice: 99.99,
    taxable: true,
    requiresShipping: true,
  },
  {
    id: "18",
    name: "Leather Tote Bag",
    description: "Spacious leather tote bag with interior pockets and magnetic closure.",
    price: 199.99,
    originalPrice: 249.99,
    rating: 4.7,
    reviewCount: 178,
    brand: "Urban Essentials",
    image: "/tan-leather-tote-bag-professional.jpg",
    images: ["/tan-leather-tote-bag-professional.jpg"],
    category: "Accessories",
    stock: 71,
    sku: "UE-TB-018",
    merchantId: "2",
    tags: ["leather", "tote", "bag", "professional"],
    featured: true,
    popularity: 90,
    variants: [{ id: "color", name: "Color", options: ["Tan", "Black", "Cognac", "Navy"] }],
    specifications: {
      Material: "Full-grain leather",
      Dimensions: "40cm x 35cm x 15cm",
      Closure: "Magnetic snap",
      Pockets: "Interior zip pocket, 2 slip pockets",
      Strap: "Dual handles, 25cm drop",
    },
    shippingInfo: "Free shipping.",
    returnPolicy: "60-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.8,
    dimensions: { length: 40, width: 35, height: 15 },
    lowStockThreshold: 15,
    trackInventory: true,
    barcode: "7890123456789",
    costPrice: 100,
    compareAtPrice: 299.99,
    taxable: true,
    requiresShipping: true,
  },
  {
    id: "19",
    name: "Cashmere Scarf",
    description: "Lightweight cashmere scarf with delicate fringe detail.",
    price: 129.99,
    rating: 4.9,
    reviewCount: 312,
    brand: "Elegance",
    image: "/grey-cashmere-scarf-with-fringe.jpg",
    images: ["/grey-cashmere-scarf-with-fringe.jpg"],
    category: "Accessories",
    stock: 124,
    sku: "EL-SC-019",
    merchantId: "2",
    tags: ["cashmere", "scarf", "luxury", "winter"],
    popularity: 87,
    variants: [{ id: "color", name: "Color", options: ["Grey", "Camel", "Navy", "Burgundy", "Black"] }],
    specifications: {
      Material: "100% Cashmere",
      Dimensions: "200cm x 70cm",
      Weight: "Lightweight",
      "Care Instructions": "Dry clean or hand wash cold",
    },
    shippingInfo: "Free shipping.",
    returnPolicy: "30-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.15,
    dimensions: { length: 25, width: 20, height: 3 },
    lowStockThreshold: 20,
    trackInventory: true,
    barcode: "8901234567890",
    costPrice: 65,
    compareAtPrice: 179.99,
    taxable: true,
    requiresShipping: true,
  },
  {
    id: "20",
    name: "Quilted Crossbody Bag",
    description: "Compact quilted crossbody bag with chain strap and multiple compartments.",
    price: 149.99,
    rating: 4.6,
    reviewCount: 189,
    brand: "LuxeJewelry",
    image: "/black-quilted-crossbody-bag-with-chain.jpg",
    images: ["/black-quilted-crossbody-bag-with-chain.jpg"],
    category: "Accessories",
    stock: 88,
    sku: "LJ-CB-020",
    merchantId: "2",
    tags: ["quilted", "crossbody", "bag", "chain"],
    popularity: 84,
    variants: [{ id: "color", name: "Color", options: ["Black", "Burgundy", "Navy", "Beige"] }],
    specifications: {
      Material: "Quilted leather",
      Dimensions: "22cm x 15cm x 7cm",
      Strap: "Chain and leather strap, adjustable",
      Closure: "Flap with turn-lock",
      Compartments: "Main compartment, interior pocket, card slots",
    },
    shippingInfo: "Standard shipping available.",
    returnPolicy: "30-day return policy.",
    status: "published",
    productType: "physical",
    weight: 0.4,
    dimensions: { length: 22, width: 15, height: 7 },
    lowStockThreshold: 15,
    trackInventory: true,
    barcode: "9012345678901",
    costPrice: 75,
    compareAtPrice: 199.99,
    taxable: true,
    requiresShipping: true,
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-001",
    userId: "3",
    userName: "Regular User",
    userEmail: "user@store.com",
    items: [
      { productId: "1", productName: "Premium Wireless Headphones", quantity: 1, price: 299.99 },
      { productId: "2", productName: "Minimalist Leather Wallet", quantity: 2, price: 59.99 },
    ],
    total: 419.97,
    status: "delivered",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "ORD-002",
    userId: "3",
    userName: "Regular User",
    userEmail: "user@store.com",
    items: [{ productId: "3", productName: "Smart Fitness Watch", quantity: 1, price: 199.99 }],
    total: 199.99,
    status: "shipped",
    createdAt: "2024-01-18T14:20:00Z",
  },
]

export const FEATURED_PRODUCTS = ["1", "3", "6", "7", "8", "11", "13", "15"] // Product IDs to feature

export const CATEGORIES: Category[] = [
  {
    id: "electronics",
    name: "Electronics",
    description: "Latest tech gadgets and accessories",
    image: "/electronics-category.png",
    productCount: 3,
  },
  {
    id: "accessories",
    name: "Accessories",
    description: "Style essentials and everyday items",
    image: "/accessories-category.png",
    productCount: 2,
  },
  {
    id: "clothing",
    name: "Clothing",
    description: "Comfortable and sustainable fashion",
    image: "/diverse-clothing-category.png",
    productCount: 1,
  },
  {
    id: "men",
    name: "Men",
    description: "Men's clothing and accessories",
    image: "/men-category.png",
    productCount: 4,
  },
  {
    id: "women",
    name: "Women",
    description: "Women's clothing and accessories",
    image: "/women-category.png",
    productCount: 4,
  },
]

export const PROMOTIONS: Promotion[] = [
  {
    id: "promo-1",
    title: "Winter Sale",
    description: "Get 20% off on all electronics",
    discount: 20,
    code: "WINTER20",
    expiresAt: "2024-02-28",
    image: "/winter-sale-banner.jpg",
  },
  {
    id: "promo-2",
    title: "Free Shipping",
    description: "Free shipping on orders over $100",
    discount: 0,
    code: "FREESHIP",
    expiresAt: "2024-12-31",
    image: "/free-shipping-banner.png",
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    productId: "1",
    userName: "John D.",
    rating: 5,
    comment: "Best headphones I've ever owned! The noise cancellation is incredible.",
    date: "2024-01-10",
    verified: true,
  },
  {
    id: "rev-2",
    productId: "1",
    userName: "Sarah M.",
    rating: 4,
    comment: "Great sound quality, but a bit heavy for long use.",
    date: "2024-01-08",
    verified: true,
  },
  {
    id: "rev-3",
    productId: "1",
    userName: "Mike R.",
    rating: 5,
    comment: "Perfect for travel and daily commute. Battery life is amazing!",
    date: "2024-01-05",
    verified: false,
  },
]
